using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace MusicControl
{
    public partial class MusicAndNumber : Form
    {
        public MusicAndNumber()
        {
            InitializeComponent();
            string[] AllMusicNameAndNumber = new string[54];
            AllMusicNameAndNumber[0] = "哀乐  罗浪编曲";
            AllMusicNameAndNumber[1] = "奥林匹克进行曲";
            AllMusicNameAndNumber[2] = "鞭炮齐鸣";
            AllMusicNameAndNumber[3] = "步步高";
            AllMusicNameAndNumber[4] = "春节序曲";
            AllMusicNameAndNumber[5] = "打靶归来";
            AllMusicNameAndNumber[6] = "分列式进行曲";
            AllMusicNameAndNumber[7] = "歌唱祖国";
            AllMusicNameAndNumber[8] = "光荣的禁卫军";
            AllMusicNameAndNumber[9] = "光荣的凯旋";
            AllMusicNameAndNumber[10] = "国歌";
            AllMusicNameAndNumber[11] = "国际歌";
            AllMusicNameAndNumber[12] = "海军进行曲";
            AllMusicNameAndNumber[13] = "欢送进行曲";
            AllMusicNameAndNumber[14] = "欢迎进行曲";
            AllMusicNameAndNumber[15] = "辉煌时刻(颁奖专用曲)";
            AllMusicNameAndNumber[16] = "瓦格纳婚礼进行曲";
            AllMusicNameAndNumber[17] = "火箭部队进行曲";
            AllMusicNameAndNumber[18] = "检阅进行曲";
            AllMusicNameAndNumber[19] = "军威进行曲";
            AllMusicNameAndNumber[20] = "卡秋莎";
            AllMusicNameAndNumber[21] = "拉德斯基进行曲";
            AllMusicNameAndNumber[22] = "没有共产党就没有新中国";
            AllMusicNameAndNumber[23] = "女兵进行曲";
            AllMusicNameAndNumber[24] = "炮兵进行曲";
            AllMusicNameAndNumber[25] = "骑兵进行曲";
            AllMusicNameAndNumber[26] = "人民海军向前进";
            AllMusicNameAndNumber[27] = "人民军队忠于党";
            AllMusicNameAndNumber[28] = "三大纪律八项注意";
            AllMusicNameAndNumber[29] = "胜利在召唤";
            AllMusicNameAndNumber[30] = "苏军进行曲";
            AllMusicNameAndNumber[31] = "团结就是力量";
            AllMusicNameAndNumber[32] = "团结友谊进行曲";
            AllMusicNameAndNumber[33] = "我们走在大路上";
            AllMusicNameAndNumber[34] = "新四军军歌";
            AllMusicNameAndNumber[35] = "学习雷锋好榜样";
            AllMusicNameAndNumber[36] = "一个斯拉夫女人的告别";
            AllMusicNameAndNumber[37] = "义勇军进行曲";
            AllMusicNameAndNumber[38] = "友谊地久天长";
            AllMusicNameAndNumber[39] = "运动员进行曲";
            AllMusicNameAndNumber[40] = "在希望的田野上";
            AllMusicNameAndNumber[41] = "葬礼进行曲  李桐树曲";
            AllMusicNameAndNumber[42] = "战车进行曲";
            AllMusicNameAndNumber[43] = "志愿军战歌";
            AllMusicNameAndNumber[44] = "中国人民解放军进行曲(铜管乐)";
            AllMusicNameAndNumber[45] = "中国人民解放军进行曲";
            AllMusicNameAndNumber[46] = "中国少年先锋队队歌";
            AllMusicNameAndNumber[47] = "中国中国鲜红的太阳永不落";
            AllMusicNameAndNumber[48] = "义勇军进行曲";
            AllMusicNameAndNumber[49] = "回家";
            AllMusicNameAndNumber[50] = "渔舟唱晚";
            AllMusicNameAndNumber[51] = "CCTV新闻联播片头";
            AllMusicNameAndNumber[52] = "欢乐斗地主背景音乐";
            AllMusicNameAndNumber[53] = "最初的梦想";
            MusicAndNumberBox.Items.Add("0 - " + AllMusicNameAndNumber[0]);
            MusicAndNumberBox.Items.Add("1 - " + AllMusicNameAndNumber[1]);
            MusicAndNumberBox.Items.Add("2 - " + AllMusicNameAndNumber[2]);
            MusicAndNumberBox.Items.Add("3 - " + AllMusicNameAndNumber[3]);
            MusicAndNumberBox.Items.Add("4 - " + AllMusicNameAndNumber[4]);
            MusicAndNumberBox.Items.Add("5 - " + AllMusicNameAndNumber[5]);
            MusicAndNumberBox.Items.Add("6 - " + AllMusicNameAndNumber[6]);
            MusicAndNumberBox.Items.Add("7 - " + AllMusicNameAndNumber[7]);
            MusicAndNumberBox.Items.Add("8 - " + AllMusicNameAndNumber[8]);
            MusicAndNumberBox.Items.Add("9 - " + AllMusicNameAndNumber[9]);
            MusicAndNumberBox.Items.Add("10 - " + AllMusicNameAndNumber[10]);
            MusicAndNumberBox.Items.Add("11 - " + AllMusicNameAndNumber[11]);
            MusicAndNumberBox.Items.Add("12 - " + AllMusicNameAndNumber[12]);
            MusicAndNumberBox.Items.Add("13 - " + AllMusicNameAndNumber[13]);
            MusicAndNumberBox.Items.Add("14 - " + AllMusicNameAndNumber[14]);
            MusicAndNumberBox.Items.Add("15 - " + AllMusicNameAndNumber[15]);
            MusicAndNumberBox.Items.Add("16 - " + AllMusicNameAndNumber[16]);
            MusicAndNumberBox.Items.Add("17 - " + AllMusicNameAndNumber[17]);
            MusicAndNumberBox.Items.Add("18 - " + AllMusicNameAndNumber[18]);
            MusicAndNumberBox.Items.Add("19 - " + AllMusicNameAndNumber[19]);
            MusicAndNumberBox.Items.Add("20 - " + AllMusicNameAndNumber[20]);
            MusicAndNumberBox.Items.Add("21 - " + AllMusicNameAndNumber[21]);
            MusicAndNumberBox.Items.Add("22 - " + AllMusicNameAndNumber[22]);
            MusicAndNumberBox.Items.Add("23 - " + AllMusicNameAndNumber[23]);
            MusicAndNumberBox.Items.Add("24 - " + AllMusicNameAndNumber[24]);
            MusicAndNumberBox.Items.Add("25 - " + AllMusicNameAndNumber[25]);
            MusicAndNumberBox.Items.Add("26 - " + AllMusicNameAndNumber[26]);
            MusicAndNumberBox.Items.Add("27 - " + AllMusicNameAndNumber[27]);
            MusicAndNumberBox.Items.Add("28 - " + AllMusicNameAndNumber[28]);
            MusicAndNumberBox.Items.Add("29 - " + AllMusicNameAndNumber[29]);
            MusicAndNumberBox.Items.Add("30 - " + AllMusicNameAndNumber[30]);
            MusicAndNumberBox.Items.Add("31 - " + AllMusicNameAndNumber[31]);
            MusicAndNumberBox.Items.Add("32 - " + AllMusicNameAndNumber[32]);
            MusicAndNumberBox.Items.Add("33 - " + AllMusicNameAndNumber[33]);
            MusicAndNumberBox.Items.Add("34 - " + AllMusicNameAndNumber[34]);
            MusicAndNumberBox.Items.Add("35 - " + AllMusicNameAndNumber[35]);
            MusicAndNumberBox.Items.Add("36 - " + AllMusicNameAndNumber[36]);
            MusicAndNumberBox.Items.Add("37 - " + AllMusicNameAndNumber[37]);
            MusicAndNumberBox.Items.Add("38 - " + AllMusicNameAndNumber[38]);
            MusicAndNumberBox.Items.Add("39 - " + AllMusicNameAndNumber[39]);
            MusicAndNumberBox.Items.Add("40 - " + AllMusicNameAndNumber[40]);
            MusicAndNumberBox.Items.Add("41 - " + AllMusicNameAndNumber[41]);
            MusicAndNumberBox.Items.Add("42 - " + AllMusicNameAndNumber[42]);
            MusicAndNumberBox.Items.Add("43 - " + AllMusicNameAndNumber[43]);
            MusicAndNumberBox.Items.Add("44 - " + AllMusicNameAndNumber[44]);
            MusicAndNumberBox.Items.Add("45 - " + AllMusicNameAndNumber[45]);
            MusicAndNumberBox.Items.Add("46 - " + AllMusicNameAndNumber[46]);
            MusicAndNumberBox.Items.Add("47 - " + AllMusicNameAndNumber[47]);
            MusicAndNumberBox.Items.Add("48 - " + AllMusicNameAndNumber[48]);
            MusicAndNumberBox.Items.Add("49 - " + AllMusicNameAndNumber[49]);
            MusicAndNumberBox.Items.Add("50 - " + AllMusicNameAndNumber[50]);
            MusicAndNumberBox.Items.Add("51 - " + AllMusicNameAndNumber[51]);
            MusicAndNumberBox.Items.Add("52 - " + AllMusicNameAndNumber[52]);
            MusicAndNumberBox.Items.Add("53 - " + AllMusicNameAndNumber[53]);
        }
    }
}
